name: Maven Package upon a push

on:
  push:
    branches:
      - 1.1.1

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Clear artifacts
        uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 10mins

      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v10
        with:
          mirrors: '[{ "id": "Artifactory", "mirrorOf": "artifactory", "url": "http://52.172.8.144:8040/artifactory" }, { "id": "MavenCentral", "mirrorOf": "central", "url": "https://repo.maven.apache.org/maven2" }]'
          repositories: '[{ "id": "Artifactory", "name": "libs-release", "url": "http://52.172.8.144:8040/artifactory/libs-release", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }, { "id": "Artifactory", "name": "libs-snapshot", "url": "http://52.172.8.144:8040/artifactory/libs-snapshot", "snapshots": { "enabled": "true" } }, { "id": "MavenCentral", "url": "https://repo.maven.apache.org/maven2", "releases": { "enabled": "true" } }]'

      - name: Build with Maven
        run: |
          mvn -v
          mvn --version
          which mvn
          echo $M2_HOME
          cp -f ~/.m2/settings.xml $GITHUB_WORKSPACE/settings.xml
          cat $GITHUB_WORKSPACE/settings.xml
          cat ~/.m2/settings.xml
          mvn clean install -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml -f authentication-partnerdemo-service/pom.xml
          #mvn clean install -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml -f pom.xml

      - name: Check local deps
        run: |
          ls -R $M2_HOME
