name: Maven Package upon a push

on:
  push:
    branches:
      - 1.1.1

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          ref: ${{ github.ref }}
          java-version: 1.8
          server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: |
          mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -DremoteRepositories=myrepo::::http://52.172.8.144:8040/artifactory/libs-release-local -Dartifact=io.mosip.authentication:authentication-partnerdemo-service:1.0.0:jar
          mvn clean install -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml -f authentication-partnerdemo-service/pom.xml
          mvn clean install -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml -f pom.xml
