name: Maven Package upon a push

on:
  push:
    branches:
      - 1.1.1

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          ref: ${{ github.ref }}
          java-version: 1.8
          server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v10
        with:
          mirrors: '[{ "id": "MavenCentral", "mirrorOf": "central", "url": "https://repo.maven.apache.org/maven2" },{ "id": "Artifactory", "mirrorOf": "artifactory", "url": "http://52.172.8.144:8040/artifactory" }]'
          repositories: '[{ "id": "MavenCentral", "url": "https://repo.maven.apache.org/maven2", "releases": { "enabled": "true" } },{ "id": "Artifactory", "url": "http://52.172.8.144:8040/artifactory", "releases": { "enabled": "true" } }]'

      - name: Build with Maven
        run: |
          mvn -v
          mvn --version
          which mvn
          echo $MAVEN_HOME
          mv -f ~/.m2/settings.xml $GITHUB_WORKSPACE/settings.xml
          cat $GITHUB_WORKSPACE/settings.xml
          cat ~/.m2/settings.xml
          #mvn clean install -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml -f authentication-partnerdemo-service/pom.xml
          #mvn clean install -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml -f pom.xml
